import Home from 'pages/Home'
import Cases from 'pages/Cases'
import Deaths from 'pages/Deaths'
import Hospitalization from 'pages/Hospitalization'
import Vaccinations from 'pages/Vaccinations'
import Testing from 'pages/Testing'
import Schools from 'pages/Schools'
import Age from 'pages/Age'
import Race from 'pages/Race'
import Gender from 'pages/Gender'
import City from 'pages/City'
import Zip from 'pages/Zip'
import WhatsOpen from 'pages/WhatsOpen'
import NoPage from 'pages/NoPage'
import Donate from 'pages/Donate'

export { Home, Cases, Deaths, Hospitalization, Vaccinations, Testing, Schools, Age, Race, Gender, City, Zip, WhatsOpen, NoPage, Donate}